// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbUz03KBFXNAytWWXfWM10UTFyNZW4PyQ',
    appId: '1:1061201854849:web:a44ed54ad61a3725566880',
    messagingSenderId: '1061201854849',
    projectId: 'crud-notif-firebase',
    authDomain: 'crud-notif-firebase.firebaseapp.com',
    storageBucket: 'crud-notif-firebase.firebasestorage.app',
    measurementId: 'G-3S5C2L8X12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBetUiQyqRFSbMJIFHVjEyXuU3jc0WKzBI',
    appId: '1:1061201854849:android:e7b589e6f5b9cd47566880',
    messagingSenderId: '1061201854849',
    projectId: 'crud-notif-firebase',
    storageBucket: 'crud-notif-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhDRHGrLjHXqSH-utj8-aL-gRDIRSB4FQ',
    appId: '1:1061201854849:ios:585aa8c1bea3b458566880',
    messagingSenderId: '1061201854849',
    projectId: 'crud-notif-firebase',
    storageBucket: 'crud-notif-firebase.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhDRHGrLjHXqSH-utj8-aL-gRDIRSB4FQ',
    appId: '1:1061201854849:ios:585aa8c1bea3b458566880',
    messagingSenderId: '1061201854849',
    projectId: 'crud-notif-firebase',
    storageBucket: 'crud-notif-firebase.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbUz03KBFXNAytWWXfWM10UTFyNZW4PyQ',
    appId: '1:1061201854849:web:64a9fd5e195258dc566880',
    messagingSenderId: '1061201854849',
    projectId: 'crud-notif-firebase',
    authDomain: 'crud-notif-firebase.firebaseapp.com',
    storageBucket: 'crud-notif-firebase.firebasestorage.app',
    measurementId: 'G-PNWC8ERK0P',
  );
}
